// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext, StoryblokAsset } from '../storyblok.d.ts';
export interface Article {
  title?: string;
  components?: (Article | Feature | FrontPage | Page | RichtextBlock)[];
  feature_image?: StoryblokAsset;
  component: "article";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface FrontPage {
  title?: string;
  features?: (ISbStoryData<Article> | string)[];
  component: "front_page";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  title?: string;
  body?: (Article | Feature | FrontPage | Page | RichtextBlock)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface RichtextBlock {
  title?: string;
  richtext?: StoryblokRichtext;
  component: "richtext_block";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Article | FrontPage | Page;
